#pragma once
// menuconfig - Kernel module configuration TUI (inside pigOS)
#include "../drivers/vga/vga.h"

#define MCFG_PATH "/etc/pigos.conf"

typedef struct { const char* key; const char* label; int val; } MCfgItem;

static MCfgItem mcfg_items[] = {
    {"BOOT_SPLASH",    "Boot splash screen",      1},
    {"BOOT_VERBOSE",   "Verbose boot",            1},
    {"VGA_DRIVER",     "VGA text driver",         1},
    {"PS2_KEYBOARD",   "PS/2 keyboard driver",    1},
    {"PS2_MOUSE",      "PS/2 mouse driver",       1},
    {"NET_RTL8139",    "RTL8139 Ethernet",        1},
    {"NET_E1000",      "Intel PRO/1000 (e1000)",  1},
    {"NET_VIRTIO",     "VirtIO Network",          1},
    {"LWIP",           "lwIP network stack",      1},
    {"LWIP_TCP",       "TCP support",             1},
    {"LWIP_UDP",       "UDP support",             1},
    {"LWIP_ICMP",      "ICMP support",            1},
    {"LWIP_DNS",       "DNS resolution",          1},
    {"LWIP_DHCP",      "DHCP client",             1},
    {"PIGFS",          "pigFS virtual FS",        1},
    {"PIGFS_PERSIST",  "Persistent storage",      1},
    {"HEAP_ALLOC",     "Heap allocator",          1},
    {"PIGSSL",         "pigSSL/TLS",              1},
    {"POING",          "poing init system",       1},
    {"USERS",          "User management",         1},
    {"LARPSHELL",      "larpshell",               1},
    {"PIGWM",          "PigWM window manager",    1},
    {"VDM",            "VDM display server",      1},
    {"PIGLOG",         "piglog logger",           1},
    {NULL, NULL, 0}
};

static int mcfg_count = 0;
static int mcfg_cursor = 0;
static int mcfg_scroll = 0;
static int mcfg_dirty = 0;
static char mcfg_buf[4096];
extern MemFile* memfs_find(const char*);
extern MemFile* memfs_create(const char*);
extern char sh_cwd[256];
extern char sh_user[32];
extern int sh_rok;

static void mcfg_load(void){
    mcfg_count = 0;
    for(int i = 0; mcfg_items[i].key; i++) mcfg_count++;

    MemFile* mf = memfs_find(MCFG_PATH);
    if(!mf || !mf->content[0]) return;

    const char* src = mf->content;
    int line_start = 0;
    for(int i = 0; ; i++){
        int is_end = (src[i] == '\n' || src[i] == '\r' || src[i] == '\0');
        if(is_end){
            int len = i - line_start;
            if(len < 8){ line_start = i + 1; continue; }

            int key_offset = 0;
            if(src[line_start] == '#'){
                key_offset = 2;
            }
            if(src[line_start+key_offset+0]!='C'||src[line_start+key_offset+1]!='O'||
               src[line_start+key_offset+2]!='N'||src[line_start+key_offset+3]!='F'||
               src[line_start+key_offset+4]!='I'||src[line_start+key_offset+5]!='G'||
               src[line_start+key_offset+6]!='_'){ line_start = i + 1; continue; }

            int key_start = line_start + key_offset + 7;
            int key_end = key_start;
            while(key_end < i && src[key_end] != '=' && src[key_end] != ' ') key_end++;

            for(int j = 0; mcfg_items[j].key; j++){
                int kl = 0;
                while(mcfg_items[j].key[kl]) kl++;
                if(key_end - key_start == kl){
                    int match = 1;
                    for(int k = 0; k < kl; k++){
                        if(src[key_start + k] != mcfg_items[j].key[k]){ match = 0; break; }
                    }
                    if(match){
                        if(src[line_start] == '#'){
                            mcfg_items[j].val = 0;
                        } else {
                            mcfg_items[j].val = (src[key_end] == '=' && src[key_end+1] == 'y') ? 1 : 0;
                        }
                        break;
                    }
                }
            }
            line_start = i + 1;
            continue;
        }
        if(src[i] == '\0') break;
    }
}

static void mcfg_save(void){
    char* buf = mcfg_buf;
    int pos = 0;

    const char* header = "# pigOS Kernel Configuration\n# Generated by menuconfig\n# Changes apply on next reboot\n\n";
    for(int i = 0; header[i]; i++) buf[pos++] = header[i];

    for(int i = 0; mcfg_items[i].key; i++){
        const char* p = "CONFIG_";
        while(*p) buf[pos++] = *p++;
        p = mcfg_items[i].key;
        while(*p) buf[pos++] = *p++;
        if(mcfg_items[i].val){
            buf[pos++] = '='; buf[pos++] = 'y';
        } else {
            buf[pos++] = ' '; buf[pos++] = 'i'; buf[pos++] = 's'; buf[pos++] = ' ';
            buf[pos++] = 'n'; buf[pos++] = 'o'; buf[pos++] = 't'; buf[pos++] = ' ';
            buf[pos++] = 's'; buf[pos++] = 'e'; buf[pos++] = 't';
        }
        buf[pos++] = '\n';
    }
    buf[pos] = 0;

    MemFile* mf = memfs_find(MCFG_PATH);
    if(!mf) mf = memfs_create(MCFG_PATH);
    if(mf){
        int copy_len = pos < 2047 ? pos : 2047;
        for(int i = 0; i < copy_len; i++) mf->content[i] = buf[i];
        mf->content[copy_len] = 0;
    }
    mcfg_dirty = 0;
}

static void cmd_menuconfig(void){
    if(ksc(sh_user, "root") != 0 && !sh_rok){
        vset(C_LRED, C_BLACK);
        vpln("menuconfig: permission denied");
        vpln("You must be root to configure kernel modules.");
        vpln("Use 'rok' to switch to root, then try again.");
        vrst();
        return;
    }

    if(ksc(sh_cwd, "/kernel") != 0){
        vset(C_LRED, C_BLACK);
        vpln("menuconfig: must be run from /kernel directory");
        vpln("Run 'cd /kernel' first, then try again.");
        vrst();
        return;
    }

    mcfg_load();
    mcfg_cursor = 0;
    mcfg_scroll = 0;
    mcfg_dirty = 0;

    // Drain any stale keys from previous command before starting
    while(kb_avail()) kb_get();

    vclear();
    int running = 1;
    int max_visible = VGA_H - 7;

    while(running){
        vclear();
        vx = 0; vy = 0;

        vfill(0, 0, VGA_W, 1, ' ', COL(C_BLACK, C_LCYAN));
        vstr(2, 0, COL(C_WHITE, C_LCYAN), " pigOS Kernel Configuration (menuconfig) ");

        vstr(1, 2, COL(C_YELLOW, C_BLACK), "UP/DOWN: navigate  SPACE: toggle  S: save  Q: quit  R: reset defaults");
        vstr(1, 3, COL(C_DGREY, C_BLACK), "-----------------------------------------------------------------------");

        if(mcfg_cursor < mcfg_scroll) mcfg_scroll = mcfg_cursor;
        if(mcfg_cursor >= mcfg_scroll + max_visible) mcfg_scroll = mcfg_cursor - max_visible + 1;

        for(int i = 0; i < max_visible; i++){
            int idx = mcfg_scroll + i;
            if(idx >= mcfg_count) break;

            int y = 5 + i;

            if(idx == mcfg_cursor){
                vat('>', COL(C_LGREEN, C_BLACK), 1, y);
            } else {
                vat(' ', COL(C_WHITE, C_BLACK), 1, y);
            }

            if(mcfg_items[idx].val){
                vat('[', COL(C_LGREEN, C_BLACK), 3, y);
                vat('*', COL(C_LGREEN, C_BLACK), 4, y);
                vat(']', COL(C_LGREEN, C_BLACK), 5, y);
            } else {
                vat('[', COL(C_DGREY, C_BLACK), 3, y);
                vat(' ', COL(C_DGREY, C_BLACK), 4, y);
                vat(']', COL(C_DGREY, C_BLACK), 5, y);
            }

            vstr(7, y, COL(C_WHITE, C_BLACK), mcfg_items[idx].label);
        }

        if(mcfg_count > max_visible){
            vstr(60, 3, COL(C_DGREY, C_BLACK), "[scroll]");
        }

        int bottom = VGA_H - 1;
        vfill(0, bottom, VGA_W, 1, ' ', COL(C_BLACK, C_DGREY));
        vstr(1, bottom, COL(C_WHITE, C_DGREY), " S=Save  Q=Quit  R=Reset  ");
        if(mcfg_dirty){
            vstr(30, bottom, COL(C_YELLOW, C_DGREY), "[*] Unsaved changes");
        }

        vga_update_hw_cursor();

        int key = kb_get();

        if(key == KEY_UP){
            if(mcfg_cursor > 0) mcfg_cursor--;
            continue;
        }
        if(key == KEY_DOWN){
            if(mcfg_cursor < mcfg_count - 1) mcfg_cursor++;
            continue;
        }
        if(key == KEY_LEFT){
            if(mcfg_cursor > 0) mcfg_cursor--;
            continue;
        }
        if(key == KEY_RIGHT){
            if(mcfg_cursor < mcfg_count - 1) mcfg_cursor++;
            continue;
        }

        switch(key){
            case ' ':
                mcfg_items[mcfg_cursor].val = !mcfg_items[mcfg_cursor].val;
                mcfg_dirty = 1;
                while(kb_avail()) kb_get();
                break;
            case 's': case 'S':
                mcfg_save();
                vfill(1, VGA_H - 2, VGA_W - 2, 1, ' ', COL(C_LGREEN, C_BLACK));
                vstr(1, VGA_H - 2, COL(C_LGREEN, C_BLACK), "Config saved! Reboot to apply changes.");
                for(volatile int i = 0; i < 50000000; i++) {}
                while(kb_avail()) kb_get();
                break;
            case 'r': case 'R':
                for(int j = 0; mcfg_items[j].key; j++) mcfg_items[j].val = 1;
                mcfg_dirty = 1;
                while(kb_avail()) kb_get();
                break;
            case 'q': case 'Q':
                while(kb_avail()) kb_get();
                running = 0;
                break;
        }

        while(kb_avail()) kb_get();
    }

    vclear();
    vrst();
}
