#!/bin/bash
# scripts/menuconfig.sh - TUI kernel config editor (Linux kernel style)
set -e

CONFIG_FILE="kernel/.config"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; WHITE='\033[1;37m'; BOLD='\033[1m'
NC='\033[0m'

declare -A CONFIG

SECTIONS=(
    "Boot Options"
    "Device Drivers"
    "Network Drivers"
    "Network Stack (lwIP)"
    "Filesystem"
    "Memory"
    "Crypto Subsystem"
    "Init System"
    "User Management"
    "Shell"
    "Window Manager"
    "Display Server"
    "Logging"
)

declare -A SECTION_DATA

SECTION_DATA["Boot Options"]="
BOOT_SPLASH|Boot splash screen|Show animated FLARE boot splash
BOOT_VERBOSE|Verbose boot|Print detailed boot messages
"

SECTION_DATA["Device Drivers"]="
VGA_DRIVER|VGA text driver|80x25 CP437 text mode @ 0xB8000
PS2_KEYBOARD|PS/2 keyboard driver|Polling-based US QWERTY keyboard
PS2_MOUSE|PS/2 mouse driver|Software cursor support
"

SECTION_DATA["Network Drivers"]="
NET_RTL8139|RTL8139 Ethernet|Realtek RTL8139 (QEMU default)
NET_E1000|Intel PRO/1000 (e1000)|Intel 82540EM (VirtualBox default)
NET_VIRTIO|VirtIO Network|Paravirtualized NIC (KVM/QEMU)
"

SECTION_DATA["Network Stack (lwIP)"]="
LWIP|lwIP network stack|Lightweight IP stack
LWIP_TCP|TCP support|Transmission Control Protocol
LWIP_UDP|UDP support|User Datagram Protocol
LWIP_ICMP|ICMP support|Ping and error messages
LWIP_DNS|DNS resolution|Domain name lookups
LWIP_DHCP|DHCP client|Automatic IP configuration
"

SECTION_DATA["Filesystem"]="
PIGFS|pigFS virtual filesystem|In-memory VFS with /dev, /etc, /proc
PIGFS_PERSIST|Persistent storage|Save files across reboots
"

SECTION_DATA["Memory"]="
HEAP_ALLOC|Heap allocator|4MB bump allocator @ 0x400000
"

SECTION_DATA["Crypto Subsystem"]="
PIGSSL|pigSSL/TLS|TLS client for HTTPS
"

SECTION_DATA["Init System"]="
POING|poing init system|Systemd-like unit manager
"

SECTION_DATA["User Management"]="
USERS|User management|Multi-user support with auth
"

SECTION_DATA["Shell"]="
LARPSHELL|larpshell|Interactive command shell
"

SECTION_DATA["Window Manager"]="
PIGWM|PigWM|Desktop window manager
"

SECTION_DATA["Display Server"]="
VDM|VDM display server|Display/Window compositor
"

SECTION_DATA["Logging"]="
PIGLOG|piglog|System event logger
"

load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        while IFS= read -r line; do
            if [[ "$line" =~ ^CONFIG_([A-Za-z0-9_]+)=y$ ]]; then
                CONFIG["${BASH_REMATCH[1]}"]="y"
            elif [[ "$line" =~ ^CONFIG_([A-Za-z0-9_]+)=m$ ]]; then
                CONFIG["${BASH_REMATCH[1]}"]="m"
            elif [[ "$line" =~ ^CONFIG_([A-Za-z0-9_]+)=([0-9]+)$ ]]; then
                CONFIG["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
            elif [[ "$line" =~ ^#\ CONFIG_([A-Za-z0-9_]+)\ is\ not\ set$ ]]; then
                CONFIG["${BASH_REMATCH[1]}"]="n"
            fi
        done < "$CONFIG_FILE"
    fi
}

save_config() {
    cat > "$CONFIG_FILE" << 'EOF'
# pigOS Kernel Configuration
# Generated by make menuconfig

EOF

    for section in "${SECTIONS[@]}"; do
        echo "# ── ${section} ─────────────────────────────────────────────" >> "$CONFIG_FILE"
        while IFS='|' read -r key label desc; do
            [[ -z "$key" ]] && continue
            val="${CONFIG[$key]:-n}"
            if [ "$val" = "y" ]; then
                echo "CONFIG_${key}=y" >> "$CONFIG_FILE"
            elif [ "$val" = "m" ]; then
                echo "CONFIG_${key}=m" >> "$CONFIG_FILE"
            elif [[ "$val" =~ ^[0-9]+$ ]]; then
                echo "CONFIG_${key}=${val}" >> "$CONFIG_FILE"
            else
                echo "# CONFIG_${key} is not set" >> "$CONFIG_FILE"
            fi
        done <<< "${SECTION_DATA[$section]}"
        echo "" >> "$CONFIG_FILE"
    done

    bash "$SCRIPT_DIR/genconfig.sh" "$CONFIG_FILE" "kernel/autoconf.h"
}

get_display() {
    local v="${CONFIG[$1]:-n}"
    case "$v" in
        y) echo -e "${GREEN}[*]${NC}" ;;
        m) echo -e "${YELLOW}[M]${NC}" ;;
        n) echo "[ ]" ;;
        *) echo "($v)" ;;
    esac
}

count_section_items() {
    local section="$1"
    local count=0
    while IFS='|' read -r key label desc; do
        [[ -z "$key" ]] && continue
        count=$((count+1))
    done <<< "${SECTION_DATA[$section]}"
    echo "$count"
}

count_enabled() {
    local section="$1"
    local enabled=0
    while IFS='|' read -r key label desc; do
        [[ -z "$key" ]] && continue
        [ "${CONFIG[$key]}" = "y" ] && enabled=$((enabled+1))
    done <<< "${SECTION_DATA[$section]}"
    echo "$enabled"
}

render_main() {
    local cursor="$1"
    clear
    echo -e "${BOLD}${CYAN}┌──────────────────────────────────────────────────────────────┐${NC}"
    echo -e "${BOLD}${CYAN}│${NC}  ${BOLD}${WHITE}pigOS Kernel Configuration${NC}                              ${BOLD}${CYAN}│${NC}"
    echo -e "${BOLD}${CYAN}├──────────────────────────────────────────────────────────────┤${NC}"
    echo -e "${BOLD}${CYAN}│${NC}  ${YELLOW}↑↓ navigate  Enter=submenu  Space=toggle  S=save  Q=quit${NC}    ${BOLD}${CYAN}│${NC}"
    echo -e "${BOLD}${CYAN}└──────────────────────────────────────────────────────────────┘${NC}"
    echo ""

    local idx=0
    for section in "${SECTIONS[@]}"; do
        local marker="  "
        [ "$idx" -eq "$cursor" ] && marker="${BOLD}${WHITE}-->${NC} "
        local total=$(count_section_items "$section")
        local enabled=$(count_enabled "$section")
        local status="${GREEN}${enabled}/${total}${NC}"
        echo -e "  ${marker}${WHITE}${section}${NC}  --->  ${status}"
        idx=$((idx+1))
    done

    echo ""
    echo -e "  ${CYAN}────────────────────────────────────────────────────────────────${NC}"
    echo -e "  ${BOLD}Save${NC}  ${WHITE}S${NC}        ${BOLD}Quit${NC}  ${WHITE}Q${NC}        ${BOLD}Load Defconfig${NC}  ${WHITE}D${NC}"
    echo ""
}

render_submenu() {
    local section="$1"
    local cursor="$2"

    clear
    echo -e "${BOLD}${CYAN}┌──────────────────────────────────────────────────────────────┐${NC}"
    echo -e "${BOLD}${CYAN}│${NC}  ${BOLD}${WHITE}pigOS Kernel Configuration${NC}                              ${BOLD}${CYAN}│${NC}"
    echo -e "${BOLD}${CYAN}├──────────────────────────────────────────────────────────────┤${NC}"
    printf "${BOLD}${CYAN}│${NC}  ${YELLOW}%-56s${NC}${BOLD}${CYAN}│${NC}\n" "$section"
    echo -e "${BOLD}${CYAN}├──────────────────────────────────────────────────────────────┤${NC}"
    echo -e "${BOLD}${CYAN}│${NC}  ${YELLOW}Space=toggle  ESC=back  S=save  Q=quit${NC}                    ${BOLD}${CYAN}│${NC}"
    echo -e "${BOLD}${CYAN}└──────────────────────────────────────────────────────────────┘${NC}"
    echo ""

    local idx=0
    while IFS='|' read -r key label desc; do
        [[ -z "$key" ]] && continue
        local marker="  "
        [ "$idx" -eq "$cursor" ] && marker="${BOLD}${WHITE}-->${NC} "
        local display=$(get_display "$key")
        echo -e "  ${marker}${display} ${WHITE}${label}${NC}"
        if [ "$idx" -eq "$cursor" ]; then
            echo -e "       ${CYAN}${desc}${NC}"
        fi
        idx=$((idx+1))
    done <<< "${SECTION_DATA[$section]}"
    echo ""
}

load_config
current_menu=-1
cursor=0

while true; do
    if [ "$current_menu" -eq -1 ]; then
        render_main "$cursor"
    else
        render_submenu "${SECTIONS[$current_menu]}" "$cursor"
    fi

    read -rsn1 key

    case "$key" in
        $'\x1b')
            read -rsn2 -t 0.1
            case "$REPLY" in
                '[A')
                    cursor=$(( (cursor - 1) ))
                    if [ "$current_menu" -eq -1 ]; then
                        [ "$cursor" -lt 0 ] && cursor=$(( ${#SECTIONS[@]} - 1 ))
                    else
                        local_total=$(count_section_items "${SECTIONS[$current_menu]}")
                        [ "$cursor" -lt 0 ] && cursor=$(( local_total - 1 ))
                    fi
                    ;;
                '[B')
                    cursor=$(( (cursor + 1) ))
                    if [ "$current_menu" -eq -1 ]; then
                        [ "$cursor" -ge "${#SECTIONS[@]}" ] && cursor=0
                    else
                        local_total=$(count_section_items "${SECTIONS[$current_menu]}")
                        [ "$cursor" -ge "$local_total" ] && cursor=0
                    fi
                    ;;
            esac
            ;;
        ' ')
            if [ "$current_menu" -ne -1 ]; then
                local idx=0
                while IFS='|' read -r k l d; do
                    [[ -z "$k" ]] && continue
                    if [ "$idx" -eq "$cursor" ]; then
                        val="${CONFIG[$k]:-n}"
                        if [ "$val" = "y" ]; then CONFIG[$k]="n"; else CONFIG[$k]="y"; fi
                        break
                    fi
                    idx=$((idx+1))
                done <<< "${SECTION_DATA[${SECTIONS[$current_menu]}]}"
            fi
            ;;
        $'\n'|'')
            if [ "$current_menu" -eq -1 ]; then
                current_menu=$cursor
                cursor=0
            fi
            ;;
        's'|'S')
            save_config
            echo -e "\n${GREEN}[OK] Config saved. kernel/autoconf.h generated.${NC}"
            read -rsn1 -t 2
            ;;
        'q'|'Q')
            clear
            exit 0
            ;;
        'd'|'D')
            cat > "$CONFIG_FILE" << 'EOF'
# pigOS Kernel Configuration - Default
CONFIG_BOOT_SPLASH=y
CONFIG_BOOT_VERBOSE=y
CONFIG_VGA_DRIVER=y
CONFIG_PS2_KEYBOARD=y
CONFIG_PS2_MOUSE=y
CONFIG_NET_RTL8139=y
CONFIG_NET_E1000=y
CONFIG_NET_VIRTIO=y
CONFIG_LWIP=y
CONFIG_LWIP_TCP=y
CONFIG_LWIP_UDP=y
CONFIG_LWIP_ICMP=y
CONFIG_LWIP_DNS=y
CONFIG_LWIP_DHCP=y
CONFIG_PIGFS=y
CONFIG_PIGFS_PERSIST=y
CONFIG_HEAP_ALLOC=y
CONFIG_PIGSSL=y
CONFIG_POING=y
CONFIG_USERS=y
CONFIG_LARPSHELL=y
CONFIG_PIGWM=y
CONFIG_VDM=y
CONFIG_PIGLOG=y
EOF
            load_config
            ;;
    esac
done
